# Site settings
title: Caneda
email: parejaobregon@gmail.com
description: "Caneda (Circuits and Networks Electronics Design Automation) is an open source EDA software focused on easy of use and portability."
baseurl: ""
url: "http://caneda.github.io"
github_username:  Caneda

# Build settings
markdown: kramdown
permalink: pretty
